### ISSUE TITLE
Non-pingable server does not fall off server list

### ISSUE THREAD

**Issue by davidjameshowell** [UnicornTranscoder/UnicornLoadBalancer#15]
Occasionally I am seeing a behavior where a removed transcoder will still show within the server list, even though it has passed the point of being pingable. I have custom scores set at 3 seconds to be considered non-pingable and a frequency of 1 second pings between LB and transcoder.

I can confirm that the timestamp does not increase and is static, but it still appears on the list. It doesn't appear to receive jobs, but I am trying to find out why if it has passed the custom score time for pingable status it is not removed. If I restart the load balancer, the transcoder disappears (since it is no longer pinging).

Have you encountered this before? If you need a bit more debug specific logs, I can attempt to gather some next time it occurs.

**Comment by Maxou44** [comment]
A disconnected transcoder will appear in the list but it will be never used to start a stream :)

**Comment by davidjameshowell** [comment]
I figured this was the unintended behavior since I did not see any sessions delegated to it. Is there a reason that the disconnected transcoder do not decay or fall off the list intentionally?

**Comment by Maxou44** [comment]
Yes, if a transcoder don't ping the LB, we keep it in the server list because streams may have been started on it and we need to forward ping/timeline requests. 

When you say "fall off the list", I suppose you watched the `/api/stats` endpoint, this url only lists the registered servers, it's not the order used to choose the best server when you start a stream, the order is based on the "score" value calculated here: https://github.com/UnicornTranscoder/UnicornLoadBalancer/blob/master/src/core/servers.js#L70
