### ISSUE TITLE
Cloudflare workers

### ISSUE THREAD

**Issue by hjone72** [UnicornTranscoder/UnicornLoadBalancer#5]
Just an enhancement idea. But with the new Cloudflare workers, a lot of the logic in here could be adapted to operate on Cloudflare. Potentially making the LB faster.

https://developers.cloudflare.com/workers/about/how-workers-work/

**Comment by Maxou44** [comment]
It's not possible, the load balancer need to access to Plex files (the sqlite database for downloads links by example). Using a cloudflare worker require to open a port for plex (32400) and PlexDirect requests will use this direct url instead of the LoadBalanacer url (and some streams will fail).

Keep in mind, the LoadBalancer isn't the performance bottleneck in this system, the biggest performance issue is Plex itself 🤣
